wmcontroller.settings:
  type: config_object
  label: 'WmController settings'
  mapping:
    settings:
      type: mapping
      mapping:
        path:
          type: string
        module:
          type: string
        theme:
          type: string
